title: Bulbapedia
author: Natali Gonzalez
email: natali.gonzalez.fmtc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page was created to inform you on all the changes there are to the new Pokemon World.

# social links
twitter_username: pokemon # DO NOT include the @ character, or else the build will fail!
github_username:  nat-gon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
